const actions = {
  FETCH_ALL_COUNTRIES_PENDING: "FETCH_ALL_COUNTRIES_PENDING",
  FETCH_ALL_COUNTRIES_SUCCEEDED: "FETCH_ALL_COUNTRIES_SUCCEEDED",
  FETCH_ALL_COUNTRIES_FAILED: "FETCH_ALL_COUNTRIES_FAILED",

  getAllCountries: () => ({
    type: actions.FETCH_ALL_COUNTRIES_PENDING
  }),

};
export default actions;
